[package]
name = "bevypr"
version = "0.1.0"
edition = "2024"
authors = ["Saad Moazzam"]

[lib]
crate-type = ["cdylib","rlib"]

[[bin]]
name = "bin"
path = "src/main.rs"

[dependencies]
bevy = "0.15.3"
bevy_panorbit_camera = "0.23.0"

[profile.release]
panic = "abort"
opt-level = 3
